# Site settings: Custom variableaccessible via {{ site.myvariable }}.
title: Raphael Raabe
undertitle: Seline Bezen
friendsURL: https://selinebezen.github.io/
email: raphael.ragnar.raabe@gmail.com
description: >-
  Offizielle Webseite des Künstlers Raphael Raabe.
en-description: >-
  Official Website of Artist Raphael Raabe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - /exclude