name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2

      - name: 0. Installing imagemagick
        run: sudo apt-get install imagemagick
      
      - name: 1. Reducing image sizes to 1600px
        run: |
          shopt -s nullglob # Sets nullglob
          shopt -s nocaseglob # Sets nocaseglob
          for f in *.{jpg,jpeg}; do
              width=$(identify -format '%w' "$f")
              height=$(identify -format '%h' "$f")
              if [ $width -gt 1600 ] && [ $height -gt 1600 ]; then
                [ $width -ge $height ] && convert -strip -thumbnail "1600" "$f" "$f" || convert -strip -thumbnail "x1600" "$f" "$f"
              fi
          done
          shopt -u nocaseglob # Unsets nocaseglob
          shopt -u nullglob # Unsets nullglob
        working-directory: img/paintings/

      - name: 2. Generating suffixes for image files
        run: |
          shopt -s nullglob # Sets nullglob
          shopt -s nocaseglob # Sets nocaseglob
          for f in *.{jpg,jpeg}; do
            nf="${f%-*}";
            # [ "${nf: -1}" = "-" ] && echo "#######bla" && nf="${f%.*}"
            [ "${#nf}" -lt 3 ] && nf="${f%.*}"
            [ "$f" != "$nf" ] && mv "$f" "$nf" && mv "$nf" "$nf.jpg";
          done

          for f in *.{jpg,jpeg}; do
            suffix=$(identify -format '%wx%h' "$f")
            mv "$f" "${f%.*}-$suffix.jpg"
          done
          shopt -u nocaseglob # Unsets nocaseglob
          shopt -u nullglob # Unsets nullglob
        working-directory: img/paintings/

      - name: 3. Generating thumbnails
        run: |
          dir_thumb="../thumb"
          [ -d "$dir_thumb" ] && rm -rf "$dir_thumb"
          mkdir "$dir_thumb"
          w=168
          shopt -s nullglob # Sets nullglob
          shopt -s nocaseglob # Sets nocaseglob
          for f in *.{jpg,jpeg}; do
            nf="thumb.${f%-*}.jpg"
            convert -strip -thumbnail "$w" "$f" "$nf" && mv $nf "$dir_thumb/"
          done
          shopt -u nocaseglob # Unsets nocaseglob
          shopt -u nullglob # Unsets nullglob
        working-directory: img/paintings/

      - name: 4. Writing paintigs.csv-file
        run: |
          fil_csv="paintings.csv"
          echo "name,orig,thumb" > $fil_csv
          shopt -s nullglob # Sets nullglob
          shopt -s nocaseglob # Sets nocaseglob
          for f in ../img/paintings/*.{jpg,jpeg}; do
            raw=$(readlink -f "$f")
            filename="${raw##*/}"
            name="${filename%.*}"
            orig="/img/paintings/$name.jpg"
            thumb="/img/thumb/thumb.${name%-*}.jpg"
            echo "$name,$orig,$thumb" >> $fil_csv
          done
          shopt -u nocaseglob # Unsets nocaseglob
          shopt -u nullglob # Unsets nullglob
        working-directory: _data/
      - name: 5. Commit and push automated preparation
        run: |
          git config --global user.name 'BOT'
          git config --global user.email 'RaphaelRaabe@users.noreply.github.com'
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes in the paintings"
          else
            git add .
            git commit -m ":robot: - AutoPrepScripts"
            git push
          fi
